form_auto_fill.settings:
  type: config_object
  label: 'ID awesome module settings'
  mapping:
    activate_auto_fill:
      type: boolean
      label: 'Auto fill create forms'
    # This distinguishes the automatic and the manual fill.
    manual_fill:
      type: boolean
      label: 'Manual fill'
    fields_to_fill:
      type: sequence
      label: 'Fields to fill'
      sequence:
        type: string
